import { FaGamepad, FaLanguage } from 'react-icons/fa';

import { BsFillGearFill } from 'react-icons/bs';
import Element from '../components/Element';
import Footer from '../components/Footer';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import React from 'react';
import Stat from '../components/Stat';
import profile from '../public/profile.png';

function aboutme({ faqs }) {
    return (
        <>
            <Head>
                <title>FAQ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className="w-screen max-w-full min-h-screen h-full bg-indigo-50 mt-16">
                <img
                    src="https://i.ibb.co/DQ4FZhL/pattern-bg.png"
                    alt="blue pattern background"
                    className="absolute w-full h-64 md:h-96 object-center object-fit z-0"
                />
                <div className="relative flex flex-col items-center justify-center sm:px-0 px-6 z-20 pb-8 lg:pb-16">
                    <div className="md:py-36 py-20">
                        <h1 role="heading" className="xl:text-6xl md:text-5xl text-3xl font-bold leading-10 text-white text-center">
                            Some info about me
                        </h1>
                    </div>
                    <div className="lg:w-1/2 md:w-8/12 sm:w-9/12 w-full space-y-6">
                        {faqs.map((faq) => (
                            <Element key={faq.id} question={faq.question} anwser={faq.anwser} />
                        ))}
                    </div>
                </div>
                <div className="w-full mx-auto flex flex-col items-center justify-center py-16">
                    <div className="w-full flex justify-center">
                        <Image src={profile} width={300} height={300} className="mx-auto rounded-full shadow-sm" alt="Profile" />
                    </div>
                    <p className="text-justify lg:text-center text-gray-600 text-base py-5 max-w-3xl mx-auto mb-8 px-8 lg:px-2">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
                        text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has
                        survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.{' '}
                    </p>
                    <div role="list" className="mx-auto w-5/6 max-w-5xl grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
                        <Stat question="Languages I know" anwser="Polish (native), English (advanced), Russian (basic)">
                            <FaLanguage className="w-12 h-12 text-indigo-400" />
                        </Stat>

                        <Stat
                            question="First piece of code I've ever written"
                            anwser="It was a java Minecraft plugin - very simple but opened my eyes">
                            <FaGamepad className="w-12 h-12 text-indigo-400" />
                        </Stat>

                        <Stat question="Getting started" anwser="Get started fast with installations">
                            <BsFillGearFill className="w-12 h-12 text-indigo-400" />
                        </Stat>

                        <Stat question="Getting started" anwser="Get started fast with installations">
                            <BsFillGearFill className="w-12 h-12 text-indigo-400" />
                        </Stat>
                    </div>
                </div>
            </main>
            <Footer />
        </>
    );
}

export default aboutme;

export async function getStaticProps() {
    const { client } = require('../graphql/client');

    const { faqs } = await client.request(`
        query MyQuery {
            faqs {
                id
                question
                anwser
            }
        }
    `);

    return {
        props: { faqs }
    };
}
