import Head from 'next/head';
import Image from 'next/image';
import workInProgress from '../public/workInProgress.svg';

export default function Home() {
    return (
        <div className="w-screen h-screen max-w-full">
            <Head>
                <title>Index Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-indigo-50 w-screen min-h-screen max-w-full flex py-32 lg:py-0">
                <div className="max-w-8xl mx-auto px-4 flex lg:space-x-20 flex-col lg:flex-row">
                    <div className="flex justify-items-center justify-center w-full lg:w-auto mx-auto">
                        <Image src={workInProgress} width={500} height={300} className="flex justify-center justify-items-center" />
                    </div>
                    <div className="flex flex-col justify-items-center justify-center space-y-8 w-full lg:w-auto text-center lg:text-left mx-auto">
                        <h1 className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-cyan-400 text-5xl lg:text-7xl font-extrabold uppercase">
                            Work in progress
                        </h1>
                        <h2 className="text-2xl lg:text-3xl text-gray-400">
                            This page is about to be completed. <br></br> Patience is a virtue
                        </h2>
                    </div>
                </div>
            </main>
        </div>
    );
}
