import Footer from '../components/Footer';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Technologies from '../components/Technologies';
import Tools from '../components/Tools';

export default function Home() {
    return (
        <div className="w-screen h-screen max-w-full">
            <Head>
                <title>Kuba Budzyński - Fullstack Developer</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Navbar />
            <main className="bg-indigo-50 w-screen min-h-screen max-w-full flex py-32 lg:py-0">
                <div className="max-w-8xl mx-auto flex flex-col">
                    <div className="w-full py-20">
                        <Technologies />
                    </div>
                    <div className="w-full pb-20">
                        <Tools />
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
