import Head from 'next/head';

export default function Home() {
    return (
        <div className="w-screen h-screen max-w-full bg-indigo-50">
            <Head>
                <title>Index Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=""></main>
        </div>
    );
}
